title: Hello DevLog!
description: > # this means to ignore newlines until "baseurl:"
  초보 WebDeveloper의 개발노트
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://hoonsdevlog.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Hoon # add your name
author-img: #david-freeman.jpg # add your photo
about-author: 끄적끄적 # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github:  # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: jh92aa@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
